# Generated by Django 3.2.6 on 2021-10-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_alter_receita_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='tempo_prepar',
            new_name='tempo_preparo',
        ),
    ]
